// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3dDh0JM87V-nYt2HFnHZ7wxSYL-us_fo',
    appId: '1:517707720001:web:d2452eec17a4e3613cedc0',
    messagingSenderId: '517707720001',
    projectId: 'fir-3bdf9',
    authDomain: 'fir-3bdf9.firebaseapp.com',
    storageBucket: 'fir-3bdf9.appspot.com',
    measurementId: 'G-TVBC1J6JVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALjkFLYIRLjKYEQubCGb6JqOQMHbShNoA',
    appId: '1:517707720001:android:ef6b8c727c82bd7c3cedc0',
    messagingSenderId: '517707720001',
    projectId: 'fir-3bdf9',
    storageBucket: 'fir-3bdf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbSE9EBR_7N7LLbgE4WdyPwmkgYaYbNt8',
    appId: '1:517707720001:ios:535a5a307efa8fdd3cedc0',
    messagingSenderId: '517707720001',
    projectId: 'fir-3bdf9',
    storageBucket: 'fir-3bdf9.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbSE9EBR_7N7LLbgE4WdyPwmkgYaYbNt8',
    appId: '1:517707720001:ios:d9028dc1f66a5f1e3cedc0',
    messagingSenderId: '517707720001',
    projectId: 'fir-3bdf9',
    storageBucket: 'fir-3bdf9.appspot.com',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
